com.hikmethankolay.user_auth_system.service.UserService Class Reference
Service class for handling user-related operations.
Public Member Functions
UserService (UserRepository userRepository, RoleRepository roleRepository, PasswordEncoder passwordEncoder, JwtUtils jwtUtils, Validator validator, LoginAttemptService loginAttemptService)
Constructor for UserService.
Page< User > findAll (Pageable pageable)
Retrieves all users with pagination.
Optional< User > findByUsernameOrEmail (String identifier)
Finds a user by username or email.
void deleteById (Long id, Long requesterId)
Deletes a user by ID.
Optional< User > findById (Long id)
Finds a user by ID.
User registerUser (UserDTO userDTO)
Registers a new user.
String authenticateUser (LoginRequestDTO loginRequest, String clientIp)
Authenticates a user.
String refreshToken (String token)
Refreshes an authentication token.
User updateUser (UserDTO updates, Long id, Long requesterId)
Detailed Description
Service class for handling user-related operations.
This service interacts with repositories to manage user authentication, validation, and user-related data.
Definition at line 44 of file UserService.java.
Constructor & Destructor Documentation
UserService()
com.hikmethankolay.user_auth_system.service.UserService.UserService (UserRepository userRepository, RoleRepository roleRepository, PasswordEncoder passwordEncoder, JwtUtils jwtUtils, Validator validator, LoginAttemptService loginAttemptService)
Constructor for UserService.
Parameters
userRepository The user repository instance.
roleRepository The role repository instance.
passwordEncoder The password encoder instance.
jwtUtils The JWT utility instance.
validator The validator instance.
Definition at line 72 of file UserService.java.
                                                                                                                                                                                                       {
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtUtils = jwtUtils;
        this.validator = validator;
        this.loginAttemptService = loginAttemptService;
    }
Member Function Documentation
authenticateUser()
String com.hikmethankolay.user_auth_system.service.UserService.authenticateUser (LoginRequestDTO loginRequest, String clientIp)
Authenticates a user.
Parameters
loginRequest The login request containing username or email and password.
clientIp The client IP for rate limiting.
Returns
A JWT token if authentication is successful, otherwise null.
Exceptions
RuntimeException if the account or IP is blocked due to too many failed login attempts.
Definition at line 156 of file UserService.java.
                                                                                  {
        String identifier = loginRequest.identifier();
        // Check if the IP address is blocked due to too many failed login attempts
        if (loginAttemptService.isBlocked(clientIp)) {
            throw new RuntimeException("Too many failed login attempts from this IP. Please try again later.");
        }
        // Check if the user is blocked due to too many failed attempts
        if (loginAttemptService.isBlocked(identifier)) {
            throw new RuntimeException("Account is temporarily locked due to too many failed login attempts. Please try again later.");
        }
        Optional<User> user = userRepository.findByUsernameOrEmail(identifier, identifier);
        if (user.isPresent() && passwordEncoder.matches(loginRequest.password(), user.get().getPassword())) {
            // Authentication successful - reset failed attempts counter
            loginAttemptService.loginSucceeded(clientIp);
            loginAttemptService.loginSucceeded(identifier);
            return jwtUtils.generateJwtToken(
                    String.valueOf(user.get().getId()),
                    user.get().getUsername(),
                    loginRequest.rememberMe()
            );
        } else {
            // Authentication failed - increment failed attempts counter
            loginAttemptService.loginFailed(clientIp);
            loginAttemptService.loginFailed(identifier);
            return null;
        }
    }
References com.hikmethankolay.user_auth_system.service.LoginAttemptService.isBlocked(), com.hikmethankolay.user_auth_system.service.LoginAttemptService.loginFailed(), and com.hikmethankolay.user_auth_system.service.LoginAttemptService.loginSucceeded().
deleteById()
void com.hikmethankolay.user_auth_system.service.UserService.deleteById (Long id, Long requesterId)
Deletes a user by ID.
Parameters
id The ID of the user to delete.
Definition at line 103 of file UserService.java.
                                                      {
        if (id.equals(requesterId)) {
            throw new RuntimeException("Cannot delete your own account");
        }
        User user = userRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("User not found with id " + id));
        userRepository.delete(user);
    }
findAll()
Page< User > com.hikmethankolay.user_auth_system.service.UserService.findAll (Pageable pageable)
Retrieves all users with pagination.
Parameters
pageable The pagination details.
Returns
A paginated list of users.
Definition at line 86 of file UserService.java.
                                                 {
        return userRepository.findAll(pageable);
    }
findById()
Optional< User > com.hikmethankolay.user_auth_system.service.UserService.findById (Long id)
Finds a user by ID.
Parameters
id The user ID.
Returns
An Optional containing the user if found.
Definition at line 119 of file UserService.java.
                                            {
        return userRepository.findById(id);
    }
Referenced by com.hikmethankolay.user_auth_system.service.UserService.refreshToken().
findByUsernameOrEmail()
Optional< User > com.hikmethankolay.user_auth_system.service.UserService.findByUsernameOrEmail (String identifier)
Finds a user by username or email.
Parameters
identifier The username or email of the user.
Returns
An Optional containing the user if found.
Definition at line 95 of file UserService.java.
                                                                   {
        return userRepository.findByUsernameOrEmail(identifier, identifier);
    }
refreshToken()
String com.hikmethankolay.user_auth_system.service.UserService.refreshToken (String token)
Refreshes an authentication token.
Parameters
token The current token to refresh.
Returns
A new JWT token if refresh is successful, otherwise null.
Definition at line 194 of file UserService.java.
                                             {
        if (token != null && jwtUtils.validateJwtToken(token) != TokenStatus.INVALID) {
            try {
                Long userId = jwtUtils.getUserIdFromJwtToken(token);
                Optional<User> userOpt = findById(userId);
                if (userOpt.isPresent()) {
                    User user = userOpt.get();
                    boolean wasRememberMe = jwtUtils.wasRememberMe(token);
                    return jwtUtils.generateJwtToken(
                            String.valueOf(user.getId()),
                            user.getUsername(),
                            wasRememberMe
                    );
                }
            } catch (Exception e) {
                // Token processing failed
                return null;
            }
        }
        return null;
    }
References com.hikmethankolay.user_auth_system.service.UserService.findById().
registerUser()
User com.hikmethankolay.user_auth_system.service.UserService.registerUser (UserDTO userDTO)
Registers a new user.
Parameters
userDTO The user information for registration.
Returns
The newly registered user entity.
Definition at line 129 of file UserService.java.
                                              {
        // Validate using Registration group
        Set<ConstraintViolation<UserDTO>> violations = validator.validate(userDTO, UserDTO.Registration.class);
        if (!violations.isEmpty()) {
            throw new ConstraintViolationException(violations);
        }
        
        checkUserUniqueness(userDTO, null);
        User user = new User();
        user.setEmail(userDTO.getEmail());
        user.setUsername(userDTO.getUsername());
        user.setPassword(passwordEncoder.encode(userDTO.getPassword()));
        // Assign default role
        assignRoleToUser(user, ERole.ROLE_USER);
        return userRepository.save(user);
    }
updateUser()
User com.hikmethankolay.user_auth_system.service.UserService.updateUser (UserDTO updates, Long id, Long requesterId)
Updates a user using the provided update DTO, applying only non-null fields. Validates the update data and ensures username/email uniqueness.
Parameters
updates DTO with update data (must not be null)
id the ID of the user to update
Returns
the updated User
Exceptions
IllegalArgumentException if updates is null
RuntimeException if the user is not found or uniqueness checks fail
Definition at line 229 of file UserService.java.
                                                                       {
        if (updates == null) {
            throw new IllegalArgumentException("Updates cannot be null");
        }
        // Validate using Update group
        Set<ConstraintViolation<UserDTO>> violations = validator.validate(updates, UserDTO.Update.class);
        if (!violations.isEmpty()) {
            throw new ConstraintViolationException(violations);
        }
        checkUserUniqueness(updates, id);
        User user = userRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("User not found with id: " + id));
        User requester = userRepository.findById(requesterId)
                .orElseThrow(() -> new RuntimeException("Requester not found with id: " + requesterId));
        boolean isAdminAction = requester.getRole() != null &&
                requester.getRole().getName().equals(ERole.ROLE_ADMIN);
        if (StringUtils.hasText(updates.getUsername())) {
            user.setUsername(updates.getUsername().trim());
        }
        if (StringUtils.hasText(updates.getEmail())) {
            user.setEmail(updates.getEmail().trim());
        }
        if (StringUtils.hasText(updates.getPassword())) {
            user.setPassword(passwordEncoder.encode(updates.getPassword().trim()));
        }
        if (updates.getRole() != null && isAdminAction) {
            assignRoleToUser(user, updates.getRole());
        }
        return userRepository.save(user);
    }
The documentation for this class was generated from the following file:
user-auth-system/src/main/java/com/hikmethankolay/user_auth_system/service/UserService.java