com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection Class Reference
Validator for validating collections of enum values.
Public Member Functions
void initialize (ValidEnum annotation)
Initializes the validator with the specified annotation parameters.
boolean isValid (Collection< String > values, ConstraintValidatorContext context)
Validates a collection of strings against the accepted enum values.
Detailed Description
Validator for validating collections of enum values.
Validates that each string in a collection matches a value in a specified enum.
Definition at line 23 of file EnumValidatorForCollection.java.
Member Function Documentation
initialize()
void com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection.initialize (ValidEnum annotation)
Initializes the validator with the specified annotation parameters.
Parameters
annotation The ValidEnum annotation instance.
Definition at line 33 of file EnumValidatorForCollection.java.
                                                 {
        this.ignoreCase = annotation.ignoreCase();
        this.acceptedValues = Arrays.stream(annotation.enumClass().getEnumConstants())
                .map(Enum::name)
                .collect(Collectors.toList());
    }
References com.hikmethankolay.user_auth_system.validator.ValidEnum.enumClass(), and com.hikmethankolay.user_auth_system.validator.ValidEnum.ignoreCase().
isValid()
boolean com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection.isValid (Collection< String > values, ConstraintValidatorContext context)
Validates a collection of strings against the accepted enum values.
Parameters
values The collection of strings to validate.
context The validation context.
Returns
True if all strings are valid enum values, otherwise false.
Definition at line 47 of file EnumValidatorForCollection.java.
                                                                                          {
        if (values == null || values.isEmpty()) {
            return true;
        }
        for (String value : values) {
            if (value == null) {
                return false;
            }
            boolean isValid = false;
            if (ignoreCase) {
                isValid = acceptedValues.stream()
                        .anyMatch(acceptedValue -> acceptedValue.equalsIgnoreCase(value));
            } else {
                isValid = acceptedValues.contains(value);
            }
            if (!isValid) {
                return false;
            }
        }
        return true;
    }
References com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection.isValid().
Referenced by com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection.isValid().
The documentation for this class was generated from the following file:
user-auth-system/src/main/java/com/hikmethankolay/user_auth_system/validator/EnumValidatorForCollection.java