com.hikmethankolay.user_auth_system.service.LoginAttemptService Class Reference
Service to prevent brute force attacks by limiting login attempts.
Public Member Functions
LoginAttemptService ()
Constructor initializing the attempts cache.
void loginSucceeded (String key)
Clears the login attempts count for successful logins.
void loginFailed (String key)
Increments the login attempts count for failed logins.
boolean isBlocked (String key)
Checks if a user is blocked due to excessive login attempts.
Detailed Description
Service to prevent brute force attacks by limiting login attempts.
This service maintains a time-based cache of login attempts, blocking users who exceed the maximum allowed number of failed attempts within a time period.
Definition at line 30 of file LoginAttemptService.java.
Constructor & Destructor Documentation
LoginAttemptService()
com.hikmethankolay.user_auth_system.service.LoginAttemptService.LoginAttemptService ()
Constructor initializing the attempts cache.
Sets up a cache that expires entries after 1 hour of inactivity.
Definition at line 42 of file LoginAttemptService.java.
                                 {
        attemptsCache = CacheBuilder.newBuilder()
                .expireAfterWrite(1, TimeUnit.HOURS)
                .build(new CacheLoader<>() {
                    @Override
                    public Integer load(String key) {
                        return 0;
                    }
                });
    }
Member Function Documentation
isBlocked()
boolean com.hikmethankolay.user_auth_system.service.LoginAttemptService.isBlocked (String key)
Checks if a user is blocked due to excessive login attempts.
Parameters
key The identifier (username or IP) to check.
Returns
True if the user has exceeded the maximum allowed attempts.
Definition at line 81 of file LoginAttemptService.java.
                                         {
        try {
            return attemptsCache.get(key) >= MAX_ATTEMPT;
        } catch (ExecutionException e) {
            return false;
        }
    }
Referenced by com.hikmethankolay.user_auth_system.service.UserService.authenticateUser().
loginFailed()
void com.hikmethankolay.user_auth_system.service.LoginAttemptService.loginFailed (String key)
Increments the login attempts count for failed logins.
Parameters
key The identifier (username or IP) of the login attempt.
Definition at line 65 of file LoginAttemptService.java.
                                        {
        int attempts;
        try {
            attempts = attemptsCache.get(key);
        } catch (ExecutionException e) {
            attempts = 0;
        }
        attempts++;
        attemptsCache.put(key, attempts);
    }
Referenced by com.hikmethankolay.user_auth_system.service.UserService.authenticateUser().
loginSucceeded()
void com.hikmethankolay.user_auth_system.service.LoginAttemptService.loginSucceeded (String key)
Clears the login attempts count for successful logins.
Parameters
key The identifier (username or IP) of the login attempt.
Definition at line 57 of file LoginAttemptService.java.
                                           {
        attemptsCache.invalidate(key);
    }
Referenced by com.hikmethankolay.user_auth_system.service.UserService.authenticateUser().
The documentation for this class was generated from the following file:
user-auth-system/src/main/java/com/hikmethankolay/user_auth_system/service/LoginAttemptService.java