com.hikmethankolay.user_auth_system.validator.ValidEnum Interface Reference
Annotation for validating enum values.
Public Member Functions
String message () default "Alan
Error message to be returned if validation fails.
Class<?>[] groups () default
Groups for validation.
Class<? extends Payload >[] payload () default
Payload for validation.
Class<? extends Enum<?> > enumClass ()
The enum class to validate against.
boolean ignoreCase () default false
Whether to ignore case during validation.
Public Attributes
değerlerinden biri olmalı.
Detailed Description
Annotation for validating enum values.
@annotation ValidEnum
Validates that a field or parameter matches a specified enum type.
Definition at line 27 of file ValidEnum.java.
Member Function Documentation
enumClass()
Class<? extends Enum<?> > com.hikmethankolay.user_auth_system.validator.ValidEnum.enumClass ()
The enum class to validate against.
Returns
The enum class.
Referenced by com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection.initialize(), com.hikmethankolay.user_auth_system.validator.EnumValidatorForEnum.initialize(), and com.hikmethankolay.user_auth_system.validator.EnumValidatorForString.initialize().
groups()
Class<?>[] com.hikmethankolay.user_auth_system.validator.ValidEnum.groups ()
Groups for validation.
Returns
The groups.
Definition at line 39 of file ValidEnum.java.
{};
ignoreCase()
boolean com.hikmethankolay.user_auth_system.validator.ValidEnum.ignoreCase ()
Whether to ignore case during validation.
Returns
True if case should be ignored, otherwise false.
Referenced by com.hikmethankolay.user_auth_system.validator.EnumValidatorForCollection.initialize(), and com.hikmethankolay.user_auth_system.validator.EnumValidatorForString.initialize().
message()
String com.hikmethankolay.user_auth_system.validator.ValidEnum.message ()
Error message to be returned if validation fails.
Returns
The error message.
Definition at line 33 of file ValidEnum.java.
{enumClass} değerlerinden biri olmalı.";
payload()
Class<? extends Payload >[] com.hikmethankolay.user_auth_system.validator.ValidEnum.payload ()
Payload for validation.
Returns
The payload.
Definition at line 45 of file ValidEnum.java.
{};
Member Data Documentation
olmalı.
değerlerinden biri com.hikmethankolay.user_auth_system.validator.ValidEnum.olmalı.
Definition at line 33 of file ValidEnum.java.
The documentation for this interface was generated from the following file:
user-auth-system/src/main/java/com/hikmethankolay/user_auth_system/validator/ValidEnum.java