Package com.hikmethankolay.user_auth_system.dto
Contains the core components of the User Authentication System.
Classes
interface UserInfo
Interface for all user details.
class UserInfoDTO
DTO for user information.
class UserRegisterDTO
DTO for user register.
class UserUpdateDTO
DTO for updating user information.
Functions
record ApiResponseDTO< T > (EApiStatus status, T data, String message)
Generic API response wrapper.
record AuthResponseDTO (String token, String tokenType)
record LoginRequestDTO (String identifier, String password, @JsonProperty(defaultValue="false") boolean rememberMe)
record RoleInfoDTO (String name, Set< RoleUserInfoDTO > users)
record RoleUserInfoDTO (Long id, String username, String email)
Detailed Description
Contains the core components of the User Authentication System.
Function Documentation
ApiResponseDTO< T >()
record com.hikmethankolay.user_auth_system.dto.ApiResponseDTO< T > (EApiStatus status, T data, String message)
Generic API response wrapper.
ApiResponseDTO
Template Parameters
T The type of the data payload.
Definition at line 28 of file ApiResponseDTO.java.
                                                                           {
}
AuthResponseDTO()
record com.hikmethankolay.user_auth_system.dto.AuthResponseDTO (String token, String tokenType)
Data Transfer Object for authentication response.
Parameters
token The authentication token.
tokenType The type of the token (e.g., "Bearer").
Authentication response DTO.
Parameters
token The authentication token.
Definition at line 22 of file AuthResponseDTO.java.
                                                              {
    public AuthResponseDTO(String token) {
        this(token, "Bearer");
    }
}
References com.hikmethankolay.user_auth_system.dto.AuthResponseDTO().
Referenced by com.hikmethankolay.user_auth_system.dto.AuthResponseDTO().
LoginRequestDTO()
record com.hikmethankolay.user_auth_system.dto.LoginRequestDTO (String identifier, String password, @JsonProperty(defaultValue="false") boolean rememberMe)
Definition at line 26 of file LoginRequestDTO.java.
                                                                                                                            {
}
References com.hikmethankolay.user_auth_system.dto.LoginRequestDTO().
Referenced by com.hikmethankolay.user_auth_system.dto.LoginRequestDTO().
RoleInfoDTO()
record com.hikmethankolay.user_auth_system.dto.RoleInfoDTO (String name, Set< RoleUserInfoDTO > users)
DTO representing role information.
Parameters
name The name of the role.
users The users assigned to the role.
Author
Hikmethan Kolay
Constructs a RoleInfoDTO from a Role entity.
Parameters
role The role entity.
Definition at line 27 of file RoleInfoDTO.java.
  {
    public RoleInfoDTO(Role role) {
        this(
                role.getName().name(),
                role.getUsers() != null
                        ? role.getUsers().stream().map(RoleUserInfoDTO::new).collect(Collectors.toSet())
                        : Set.of()
        );
    }
}
References com.hikmethankolay.user_auth_system.dto.RoleInfoDTO().
Referenced by com.hikmethankolay.user_auth_system.dto.RoleInfoDTO().
RoleUserInfoDTO()
record com.hikmethankolay.user_auth_system.dto.RoleUserInfoDTO (Long id, String username, String email)
Constructs a RoleUserInfoDTO from a User entity.
Parameters
user The user entity.
Definition at line 29 of file RoleUserInfoDTO.java.
  {
    public RoleUserInfoDTO(User user) {
        this(
                user.getId(),
                user.getUsername(),
                user.getEmail()
        );
    }
}
References com.hikmethankolay.user_auth_system.dto.RoleUserInfoDTO().
Referenced by com.hikmethankolay.user_auth_system.dto.RoleUserInfoDTO().